language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t henrikig/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true henrikig/docker-react npm run test -- --coverage
    